routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/homes', 'HomeController@synctes')->name('homes');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('jabatan/data', 'JabatanController@getData')->name('jabatan.data');
Route::get('karyawan/data', 'KaryawanController@getData')->name('karyawan.data');
Route::get('karyawan/sync', 'KaryawanController@sync')->name('karyawan.sync');
Route::post('karyawan/excel', 'KaryawanController@generateExcel')->name('karyawan.excel');
Route::get('payroll', 'PayrollController@index')->name('payroll');
Route::get('payroll/data', 'PayrollController@getData')->name('payroll.data');
Route::post('payroll/pdf', 'PayrollController@generatePdf')->name('payroll.pdf');
Route::get('payroll/pdf/{id_payroll}', 'PayrollController@generateSinglePdf')->name('payroll.singlepdf');
Route::get('payroll/email', 'PayrollController@sendEmail')->name('payroll.email');
Route::post('payroll/multi-email', 'PayrollController@sendMultiEmail')->name('payroll.multi-email');
Route::post('payroll/prn', 'PayrollController@getListPrn')->name('payroll.prn');
Route::post('payroll/sync', 'PayrollController@syncPayroll')->name('payroll.sync');
Route::put('payroll/lain-lain/save', 'PayrollController@setLainLain')->name('payroll.lain-lain.save');
Route::get('payroll/lain-lain/{id_payroll}', 'PayrollController@getLainLain')->name('payroll.lain-lain');
Route::get('payroll/form-import-tunjangan', 'PayrollController@formImportTunjangan')->name('payroll.form-import-tunjangan');
Route::get('payroll/{payroll}', 'PayrollController@show');
Route::post('payroll/import-tunjangan', 'PayrollController@importTunjangan')->name('payroll.import-tunjangan');
Route::post('payroll/import-pph', 'PayrollController@importPph')->name('payroll.import-pph');
Route::get('pengaturan', 'ConfigController@index')->name('config');
Route::post('pengaturan/save', 'ConfigController@save')->name('config-save');
Route::post('pengaturan/upload', 'ConfigController@upload')->name('config-upload');
Route::get('profile', 'UserController@profile')->name('profile');
Route::put('profile/change-password', 'UserController@changePassword')->name('profile.change-password');
Route::get('thr', 'ThrController@index')->name('thr.index');
Route::get('thr/data', 'ThrController@getData')->name('thr.data');
Route::get('thr/hitung', 'ThrController@hitung')->name('thr.hitung');
Route::get('pph', 'PphController@index')->name('pph.index');
Route::get('pph/data', 'PphController@getData')->name('pph.data');
Route::get('pph/pdf', 'PphController@pdf')->name('pph.pdf');
Route::get('pph/detail', 'PphController@getDetail')->name('pph.detail');
Route::put('pph/update', 'PphController@update')->name('pph.update');

// testing only
Route::get('payroll/test', 'PayrollController@test')->name('payroll.test');

Route::resources([
    'karyawan' => 'KaryawanController',
    'jabatan' => 'JabatanController',
    'user' => 'UserController',
]);

app/Karyawan.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Karyawan extends Model
{
    //
    protected $table = 'karyawan';
    protected $primaryKey = 'id_karyawan';
    protected $guarded = [];
    protected $casts = [
        'prn' => 'string',
        'tgl_masuk' => 'datetime:Y-m-d',
    ];

    public function getTunjanganJabatanAttribute() {
        $prn = $this->attributes['prn'];

        if (substr($prn, 0, 2) == '05') {
            return 0;
        }

        return $this->jabatan->tunjangan_jabatan;
    }

    public function getNamaAttribute() {
        if (isset($this->attributes['nama'])) {
            return ucwords($this->attributes['nama']);
        } else {
            return null;
        }
    }

    public function setNamaAttribute($value) {
        $this->attributes['nama'] = ucwords($value);
    }

    public function getTglMasukAttribute() {
        if (isset($this->attributes['tgl_masuk'])) {
            return Carbon::parse($this->attributes['tgl_masuk'])->format('d/m/Y');
        } else {
            return '';
        }
    }

    public function getCarbonTglMasukAttribute() {
        if (isset($this->attributes['tgl_masuk'])) {
            return Carbon::parse($this->attributes['tgl_masuk']);
        } else {
            return null;
        }
    }

    public function setTglMasukAttribute($value) {
        $this->attributes['tgl_masuk'] = Carbon::createFromFormat('d/m/Y', $value)->format('Y-m-d') . " 00:00:00";
    }

    public function jabatan(){
        return $this->belongsTo('App\Jabatan', 'id_jabatan', 'id_jabatan');
    }

    public function getRealValue($percent)
    {
        return $this->attributes['gaji_pokok'] * ($percent / 100);
    }
}

app/Http/Controllers/KaryawanController.php
<?php

namespace App\Http\Controllers;

use App\Jabatan;
use App\Karyawan;
use App\WebToto;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Yajra\Datatables\Datatables;

class KaryawanController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        session(['prev-karyawan' => request()->path()]);
        $seksi = DB::table('karyawan')->select(DB::raw('DISTINCT seksi'))->get()->toArray();
        // return var_dump($seksi);
        return view('karyawan.index', compact('seksi'));
    }

    public function sync()
    {
        $webToto = new WebToto();
        $this->syncAllJabatan($webToto);
        $this->syncAllKaryawan($webToto);
    }

    private function syncAllJabatan(WebToto $webToto)
    {
        $real_jabatan = $webToto->getAllJabatan();
        // if($real_jabatan) return;

        $akuntansi_jabatan = Jabatan::all();
        $pointer = 0;

        // dd($akuntansi_jabatan, $real_jabatan);
        $length_real_jabatan = count($real_jabatan);
        foreach ($akuntansi_jabatan as $a_j) {
            while ($pointer < $length_real_jabatan
                && strcmp($a_j->id_jabatan, $real_jabatan[$pointer]->id_jabatan) == 1) {

                //tambah;
                $this->syncJabatan($real_jabatan[$pointer]);
                $pointer++;
            }
            if ($pointer >= $length_real_jabatan
                || strcmp($a_j->id_jabatan, $real_jabatan[$pointer]->id_jabatan) == -1) {
                //hapus;
            } else if (strcmp($a_j->id_jabatan, $real_jabatan[$pointer]->id_jabatan) == 0) {
                //check;
                //echo "cheking ".$a_j->nama."<br>";
                if ($a_j->nama != $real_jabatan[$pointer]->nama) {

                    //echo "updating ".$a_j->nama."<br>";
                    $this->syncJabatan($real_jabatan[$pointer]);
                }
                $pointer++;
            }
        }
        while ($pointer < $length_real_jabatan) {
            //tambah;
            $this->syncJabatan($real_jabatan[$pointer]);
            $pointer++;
        }
    }

    private function syncJabatan($tmp_jabatan, $new_jabatan = null)
    {
        if ($new_jabatan == null) $new_jabatan = new Jabatan;
        $new_jabatan->id_jabatan = $tmp_jabatan->id_jabatan;
        $new_jabatan->nama = $tmp_jabatan->nama;
        $new_jabatan->save();
    }

    private function syncAllKaryawan(WebToto $webToto)
    {
        $karyawan_hris = $webToto->getAllKaryawan();

        $akuntansi_karyawan = Karyawan::orderBy('id_karyawan', 'asc')->get();
        $pointer = 0;
        $length_karyawan_hris = count($karyawan_hris);

        foreach ($akuntansi_karyawan as $a_k) {
            while ($pointer < $length_karyawan_hris
                && $a_k->id_karyawan > $karyawan_hris[$pointer]->id_karyawan) {
                // tambah;
                $this->syncKaryawan($karyawan_hris[$pointer]);
                $pointer++;
            }

            if ($pointer < $length_karyawan_hris && $a_k->id_karyawan == $karyawan_hris[$pointer]->id_karyawan) {
                // check;
                if ($a_k->updated_at != $karyawan_hris[$pointer]->updated_at) {
                    // update
                    $this->syncKaryawan($karyawan_hris[$pointer], $a_k);
                }
                $pointer++;
            } else if ($a_k->id_karyawan < $karyawan_hris[$pointer]) {
                //hapus;
                $a_k->delete();
            }
        }

        while ($pointer < $length_karyawan_hris) {
            //tambah;
            $this->syncKaryawan($karyawan_hris[$pointer]);
            $pointer++;
        }
    }

    private function syncKaryawan($tmp_karyawan, $a_k = null)
    {
        if ($a_k == null) {
            $a_k = new Karyawan;
        }

        $a_k->id_karyawan = $tmp_karyawan->id_karyawan;
        $a_k->prn = $tmp_karyawan->prn;
        $a_k->nama = $tmp_karyawan->nama;
        $a_k->email = $tmp_karyawan->email;
        $a_k->npwp = $tmp_karyawan->no_npwp;
        $a_k->nik = $tmp_karyawan->no_ktp;
        $a_k->alamat = $tmp_karyawan->alamat_ktp;
        $a_k->jenis_kelamin = $tmp_karyawan->jenis_kelamin;
        $a_k->status_kawin = $tmp_karyawan->status_kawin;
        $a_k->id_jabatan = $tmp_karyawan->id_jabatan;
        $a_k->seksi = $tmp_karyawan->seksi;
        $a_k->tgl_masuk = date('d/m/Y', strtotime($tmp_karyawan->tgl_masuk));
        $a_k->ptkp = $tmp_karyawan->ptkp;
        $a_k->status = $tmp_karyawan->tgl_resign === null ? 'Aktif' : 'Resign';
        $a_k->tgl_resign = $tmp_karyawan->tgl_resign ?? null;
        $a_k->created_at = $tmp_karyawan->created_at;
        $a_k->updated_at = $tmp_karyawan->updated_at;
        $a_k->save();
    }

    public function getData(Request $request)
    {
        $wheres = [];

        if ($request->seksi != null) {
            $wheres['karyawan.seksi'] = $request->seksi;
        }

        if ($request->id_jabatan != null) {
            $wheres['karyawan.id_jabatan'] = $request->id_jabatan;
        }

        if (count($wheres) > 0) {
            $query = DB::table('karyawan')
                ->join('jabatan', 'karyawan.id_jabatan', '=', 'jabatan.id_jabatan')
                ->select('karyawan.*', DB::raw('jabatan.nama as nama_jabatan'))
                ->where($wheres);
        } else {
            $query = DB::table('karyawan')
                ->join('jabatan', 'karyawan.id_jabatan', '=', 'jabatan.id_jabatan')
                ->select('karyawan.*', DB::raw('jabatan.nama as nama_jabatan'));
        }

        return Datatables::of($query)
            ->addIndexColumn()
            ->addColumn('jabatan', function ($karyawan) {
                if ($karyawan->id_jabatan !== NULL) {
                    return $karyawan->nama_jabatan;
                } else {
                    return "Tidak ada jabatan";
                }
            })
            ->editColumn('gaji_pokok', '{!! "Rp" . number_format($gaji_pokok,2,",",".") !!}')
            ->addColumn('action', function ($karyawan) {
                return view('karyawan.buttons', compact('karyawan'));
            })
            ->rawColumns(['action'])
            ->filterColumn('jabatan', function ($query, $keyword) {
                $sql = "jabatan.nama like ?";
                $query->whereRaw($sql, ["%{$keyword}%"]);
            })
            ->orderColumn('jabatan', function ($query, $order) {
                $query->orderBy('jabatan.nama', $order);
            })
            ->toJson();
    }

    public function generateExcel(Request $request)
    {
        $wheres = [];

        if ($request->seksi != null) {
            $wheres['karyawan.seksi'] = $request->seksi;
        }

        if ($request->id_jabatan != null) {
            $wheres['karyawan.id_jabatan'] = $request->id_jabatan;
        }

        if (count($wheres) > 0) {
            $karyawan = DB::table('karyawan')
                ->join('jabatan', 'karyawan.id_jabatan', '=', 'jabatan.id_jabatan')
                ->select('karyawan.*', DB::raw('jabatan.nama as nama_jabatan'))
                ->where($wheres)
                ->get();
        } else {
            $karyawan = DB::table('karyawan')
                ->join('jabatan', 'karyawan.id_jabatan', '=', 'jabatan.id_jabatan')
                ->select('karyawan.*', DB::raw('jabatan.nama as nama_jabatan'))
                ->get();
        }

        $spreadsheet = new Spreadsheet;
        $sheet = $spreadsheet->getActiveSheet();
        $data = [];

        foreach ($karyawan as $k) {
            $data[] = [
                $k->nama,
                $k->prn,
                $k->seksi
            ];
        }

        $sheet->fromArray(
            $data,
            null,
            'A3'
        );

        $writer = new Xlsx($spreadsheet);
        $writer->save("./excel/data_karyawan_SPN.xlsx");

        return dd($karyawan);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param Karyawan $karyawan
     *
     * @return Response
     */
    public function show(Karyawan $karyawan)
    {
        return json_encode($karyawan);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Karyawan $karyawan
     *
     * @return Response
     */
    public function edit(Karyawan $karyawan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Karyawan $karyawan
     *
     * @return Response
     */
    public function update(Request $request, Karyawan $karyawan)
    {
        $karyawan->update($request->all());

        return 'Berhasil mengupdate data karyawan!';
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Karyawan $karyawan
     *
     * @return Response
     */
    public function destroy(Karyawan $karyawan)
    {
        //
    }

}

resources/views/karyawan/buttons.blade.php
<div class="button-group">
    {{-- <a href="{{ route('karyawan.show', $karyawan->id_karyawan) }}" class="btn btn-info btn-sm btn-icon btn-icon-style-1"><span class="btn-icon-wrap"><i class="material-icons">pageview</i></span></a> --}}
    <button id="btn-edit" value="{{ $karyawan->id_karyawan }}" class="btn btn-success btn-sm btn-icon btn-icon-style-1"><span class="btn-icon-wrap"><i class="material-icons">edit</i></span></button>
</div>

resources/views/karyawan/form-keluarga.blade.php
@extends('layouts.app')

@isset($keluarga)
    @section('title', 'Ubah Keluarga - '.$karyawan->nama)

    @php
        $action = route('karyawan.edit-keluarga', compact('karyawan', 'keluarga'));
        $method = method_field('PUT');
    @endphp
@endisset

@push('stylesheets')
<!-- Daterangepicker CSS -->
<link href="{{ asset('vendors/daterangepicker/daterangepicker.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('vendors/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
@endpush

@section('breadcrumb')
    {{ Breadcrumbs::render('karyawan.add-keluarga', $karyawan) }}
@endsection

@empty($keluarga)
    @section('title', 'Tambah Keluarga - '.$karyawan->nama)

    @php
        $keluarga = new \App\Keluarga();
        $action = route('karyawan.add-keluarga', $karyawan);
        $method = method_field('POST');
    @endphp
@endempty

@section('content')
<section class="hk-sec-wrapper col-md-10 offset-md-1 col-sm-12">
    <h5 class="hk-sec-title">Tambah Keluarga {{ $karyawan->nama }}</h5>
    <form id="myform" action="{{ $action }}" method="POST">
        {{ $method }}
        @csrf
        <input name="id_karyawan" type="hidden" class="form-control" value="{{ $karyawan->id_karyawan }}">
        <div class="form-group">
            <label for="nama_lengkap">Nama Lengkap</label>
            <input name="nama_lengkap" type="text" class="form-control" value="{{ $keluarga->nama_lengkap }}">
        </div>
        <div class="row">
            <div class="form-group col-md-6 col-xs-12">
                <label for="nik">Nomor KTP (NIK)</label>
                <input name="nik" type="text" class="form-control" value="{{ $keluarga->nik }}">
            </div>
            <div class="form-group col-md-6 col-xs-12">
                <label for="no_kk">Nomer KK</label>
                <input name="no_kk" type="text" class="form-control" value="{{ $keluarga->no_kk }}">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label mb-10">Jenis Kelamin</label>
            <div class="pl-3">
                <div class="custom-radio form-check-inline">
                    <input id="radio_male" value="Laki-laki" name="jenis_kelamin" class="custom-control-input form-check-input"
                    @if ($keluarga->jenis_kelamin != "Perempuan")
                        checked
                    @endif
                    type="radio">
                    <label for="radio_male" class="custom-control-label">Laki-laki</label>
                </div>
                <div class="custom-radio form-check-inline">
                    <input id="radio_female" value="Perempuan" name="jenis_kelamin" class="custom-control-input form-check-input"
                    @if ($keluarga->jenis_kelamin == "Perempuan")
                        checked
                    @endif
                    type="radio">
                    <label for="radio_female" class="custom-control-label">Perempuan</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6 col-xs-12">
                <label for="tempat_lahir">Tempat Lahir</label>
                <input name="tempat_lahir" type="text" placeholder="Nama Kabupaten/Kota" class="form-control" value="{{ $keluarga->tempat_lahir }}">
            </div>
            <div class="form-group col-md-6 col-xs-12">
                <label for="tgl_lahir">Tanggal Lahir</label>
                <input name="tgl_lahir" type="text" class="form-control single-date-picker" value="{{ $keluarga->tgl_lahir }}">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6 col-xs-12">
                <label for="status_perkawinan">Status Kawin</label>
                <select name="status_perkawinan" class="form-control select2">
                    <option></option>
                    @foreach (['Belum kawin', 'Sudah kawin'] as $text)
                        <option value="{{ $text }}" @if ($keluarga->status_perkawinan == $text)
                            selected
                        @endif>{{ $text }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-md-6 col-xs-12">
                <label for="status_keluarga">Hubungan dengan karyawan</label>
                <select name="status_keluarga" class="form-control select2">
                    <option></option>
                    @foreach (['Ayah', 'Ibu', 'Istri', 'Suami', 'Anak', 'Kakak', 'Adik', 'Kakek', 'Nenek', 'Paman', 'Bibi', 'Keponakan'] as $item)
                        <option value="{{ $item }}" @if ($keluarga->status_keluarga == $item)
                            selected
                        @endif>{{ $item }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">
            Simpan
		</button>
    </form>
</section>
@endsection

@push('scripts')

<!-- Jasny-bootstrap  JavaScript -->
<script src="{{ asset('vendors/jasny-bootstrap/dist/js/jasny-bootstrap.min.js') }}"></script>
<!-- Select2 JavaScript -->
<script src="{{ asset('vendors/select2/dist/js/select2.min.js') }}"></script>
<!-- Form Wizard JavaScript -->
<script src="{{ asset('vendors/jquery-steps/build/jquery.steps.min.js') }}"></script>
<!-- Dropify JavaScript -->
<script src="{{ asset('vendors/dropify/dist/js/dropify.min.js') }}"></script>
<!-- Laravel Javascript Validation -->
<script type="text/javascript" src="{{ url('js/jsvalidation.js')}}"></script>
{!! JsValidator::formRequest('App\Http\Requests\GeneralRequest', '#myform') !!}

<!-- Daterangepicker JavaScript -->
<script src="{{ asset('vendors/select2/dist/js/select2.min.js') }}"></script>
<script src="{{ asset('vendors/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('vendors/daterangepicker/daterangepicker.js') }}"></script>
<script>
$(document).ready(function(){
    var myform = $('#myform');
    var validator = $('#myform').data("validator");

    $('.timepicker').daterangepicker({
        opens: 'left',
        singleDatePicker: true,
        timePicker: true,
        timePicker24Hour: true,
        "cancelClass": "btn-secondary",
        locale: {
		  format: 'H:mm'
        },
        showDropdowns: true,
    });

    $('.single-date-picker').daterangepicker({
        singleDatePicker: true,
		showDropdowns: true,
        cancelClass: "btn-secondary",
        locale: {
           format: 'DD/MM/YYYY'
        }
    });

    $('.select2').select2({
        allowClear: true,
        placeholder: '--- Pilih ---',
    });

    $(document).on("change", ".select2", function() {
        validator.element(this);
    });

	$('.timepicker').focusin(function(){
		$('.calendar-table').css("display","none");
    });
});
</script>
@endpush