routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/homes', 'HomeController@synctes')->name('homes');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('jabatan/data', 'JabatanController@getData')->name('jabatan.data');
Route::get('karyawan/data', 'KaryawanController@getData')->name('karyawan.data');
Route::get('karyawan/sync', 'KaryawanController@sync')->name('karyawan.sync');
Route::post('karyawan/excel', 'KaryawanController@generateExcel')->name('karyawan.excel');
Route::get('payroll', 'PayrollController@index')->name('payroll');
Route::get('payroll/data', 'PayrollController@getData')->name('payroll.data');
Route::post('payroll/pdf', 'PayrollController@generatePdf')->name('payroll.pdf');
Route::get('payroll/pdf/{id_payroll}', 'PayrollController@generateSinglePdf')->name('payroll.singlepdf');
Route::get('payroll/email', 'PayrollController@sendEmail')->name('payroll.email');
Route::post('payroll/multi-email', 'PayrollController@sendMultiEmail')->name('payroll.multi-email');
Route::post('payroll/prn', 'PayrollController@getListPrn')->name('payroll.prn');
Route::post('payroll/sync', 'PayrollController@syncPayroll')->name('payroll.sync');
Route::put('payroll/lain-lain/save', 'PayrollController@setLainLain')->name('payroll.lain-lain.save');
Route::get('payroll/lain-lain/{id_payroll}', 'PayrollController@getLainLain')->name('payroll.lain-lain');
Route::get('payroll/form-import-tunjangan', 'PayrollController@formImportTunjangan')->name('payroll.form-import-tunjangan');
Route::get('payroll/{payroll}', 'PayrollController@show');
Route::post('payroll/import-tunjangan', 'PayrollController@importTunjangan')->name('payroll.import-tunjangan');
Route::post('payroll/import-pph', 'PayrollController@importPph')->name('payroll.import-pph');
Route::get('pengaturan', 'ConfigController@index')->name('config');
Route::post('pengaturan/save', 'ConfigController@save')->name('config-save');
Route::post('pengaturan/upload', 'ConfigController@upload')->name('config-upload');
Route::get('profile', 'UserController@profile')->name('profile');
Route::put('profile/change-password', 'UserController@changePassword')->name('profile.change-password');
Route::get('thr', 'ThrController@index')->name('thr.index');
Route::get('thr/data', 'ThrController@getData')->name('thr.data');
Route::get('thr/hitung', 'ThrController@hitung')->name('thr.hitung');
Route::get('pph', 'PphController@index')->name('pph.index');
Route::get('pph/data', 'PphController@getData')->name('pph.data');
Route::get('pph/pdf', 'PphController@pdf')->name('pph.pdf');
Route::get('pph/detail', 'PphController@getDetail')->name('pph.detail');
Route::put('pph/update', 'PphController@update')->name('pph.update');

// testing only
Route::get('payroll/test', 'PayrollController@test')->name('payroll.test');

Route::resources([
    'karyawan' => 'KaryawanController',
    'jabatan' => 'JabatanController',
    'user' => 'UserController',
]);

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@yield('title', config('app.name'))</title>
    <meta name="description" content="Human Resource and Payroll Web App" />

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Favicon -->
    <link rel="icon" href="{{ asset('dist/img/favicon-16x16.png') }}" sizes="16x16" type="image/png">
    <link rel="icon" href="{{ asset('dist/img/favicon-32x32.png') }}" sizes="32x32" type="image/png">
    <link rel="icon" href="{{ asset('dist/img/favicon-96x96.png') }}" sizes="96x96" type="image/png">

    @stack('stylesheets')

    <!-- Toggles CSS -->
    <link href="{{ asset('vendors/jquery-toggles/css/toggles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('vendors/jquery-toggles/css/themes/toggles-light.css') }}" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="{{ asset('dist/css/style.css') }}" rel="stylesheet" type="text/css">
</head>

<body>
    <!-- Preloader -->
    <div class="preloader-it">
        <div class="loader-pendulums"></div>
    </div>
    <!-- /Preloader -->

	<!-- HK Wrapper -->
	<div class="hk-wrapper hk-vertical-nav">

        @include('layouts.top')

        @include('layouts.left')

        <!-- Main Content -->
        <div class="hk-pg-wrapper">

			<!-- Container -->
            <div class="container-fluid mt-30">

                <!-- Row -->
                <div class="row">
                    <div class="col-xl-12">
                        @yield('content')
                    </div>
                </div>
                <!-- /Row -->
            </div>
            <!-- /Container -->

            <!-- Footer -->
            <div class="hk-footer-wrap container">
                <footer class="footer">
                    <div class="row">
                        <div class="col-md-12">
                            <p>Powered by<a href="https:/dig-ind.com/" class="text-dark" target="_blank">Digital Indonesia</a> © 2019</p>
                        </div>
                    </div>
                </footer>
            </div>
            <!-- /Footer -->
        </div>
        <!-- /Main Content -->

    </div>
    <!-- /HK Wrapper -->

    <!-- jQuery -->
    <script src="{{ asset('vendors/jquery/dist/jquery.min.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('vendors/popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>

    <!-- Slimscroll JavaScript -->
    <script src="{{ asset('dist/js/jquery.slimscroll.js') }}"></script>

    <!-- Fancy Dropdown JS -->
    <script src="{{ asset('dist/js/dropdown-bootstrap-extended.js') }}"></script>

    <!-- FeatherIcons JavaScript -->
    <script src="{{ asset('dist/js/feather.min.js') }}"></script>

    <!-- Init JavaScript -->
    <script src="{{ asset('dist/js/init.js') }}"></script>

    @stack('scripts')
</body>

</html>

resources/views/layouts/appblank.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/left.blade.php
@php
    $route = explode('.',Route::currentRouteName())[0];
@endphp
<!-- Vertical Nav -->
<nav class="hk-nav hk-nav-light">
    <a href="javascript:void(0);" id="hk_nav_close" class="hk-nav-close"><span class="feather-icon"><i data-feather="x"></i></span></a>
    <div class="nicescroll-bar">
        <div class="navbar-nav-wrap">
            <ul class="navbar-nav flex-column">
                <li class="nav-item {{ $route === 'dashboard' ? 'active' : null }}">
                    <a class="nav-link" href="{{ route('dashboard') }}">
                        <span class="feather-icon"><i data-feather="home"></i></span>
                        <span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item {{ $route === 'karyawan' ? 'active' : null }}">
                    <a class="nav-link" href="{{ route('karyawan.index') }}">
                        <span class="feather-icon"><i data-feather="users"></i></span>
                        <span class="nav-link-text">Karyawan</span>
                    </a>
                </li>
                <li class="nav-item {{ $route === 'jabatan' ? 'active' : null }}">
                    <a class="nav-link" href="{{ route('jabatan.index') }}">
                        <span class="feather-icon"><i data-feather="award"></i></span>
                        <span class="nav-link-text">Jabatan</span>
                    </a>
                </li>
                <li class="nav-item {{ $route === 'payroll' ? 'active' : null }}">
                    <a class="nav-link" href="{{ route('payroll') }}">
                        <span class="feather-icon"><i data-feather="credit-card"></i></span>
                        <span class="nav-link-text">Payroll</span>
                    </a>
                </li>
                <li class="nav-item {{ $route === 'thr' ? 'active' : null }}">
                    <a class="nav-link" href="{{ route('thr.index') }}">
                        <span class="feather-icon"><i data-feather="gift"></i></span>
                        <span class="nav-link-text">THR</span>
                    </a>
                </li>
                <li class="nav-item {{ $route === 'pph' ? 'active' : null }}">
                    <a class="nav-link" href="{{ route('pph.index') }}">
                        <span class="feather-icon"><i data-feather="file"></i></span>
                        <span class="nav-link-text">PPH 21</span>
                    </a>
                </li>
                <li class="nav-item {{ $route === 'config' ? 'active' : null }}">
                    <a class="nav-link" href="{{ route('config') }}">
                        <span class="feather-icon"><i data-feather="sliders"></i></span>
                        <span class="nav-link-text">Pengaturan</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div id="hk_nav_backdrop" class="hk-nav-backdrop"></div>
<!-- /Vertical Nav -->

resources/views/layouts/top.blade.php
<!-- Top Navbar -->
<nav class="navbar navbar-expand-xl navbar-light fixed-top hk-navbar">
    <a id="navbar_toggle_btn" class="navbar-toggle-btn nav-link-hover" href="javascript:void(0);"><span class="feather-icon"><i data-feather="menu"></i></span></a>
    <a class="navbar-brand" href="dashboard1.html">
        <img class="brand-img d-inline-block" src="{{ asset('dist/img/logo-toto.png') }}" alt="Logo TOTO" />
    </a>
    <ul class="navbar-nav hk-navbar-content">
        <li class="nav-item dropdown dropdown-authentication">
            <a class="nav-link dropdown-toggle no-caret" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media">
                    <div class="media-body">
                        <span>{{ Auth::user()->name }}<i class="zmdi zmdi-chevron-down"></i></span>
                    </div>
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
                <a class="dropdown-item" href="{{ route('profile') }}"><i class="dropdown-icon zmdi zmdi-account"></i><span>Profil</span></a>
                <a class="dropdown-item" href="{{ route('profile.change-password') }}"><i class="dropdown-icon zmdi zmdi-key"></i><span>Ubah Password</span></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"  href="{{ route('logout') }}"
                onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                    <i class="dropdown-icon zmdi zmdi-power"></i>
                    <span>Log out</span>
                </a>
            </div>
        </li>
    </ul>
</nav>
<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
</form>
{{-- <form role="search" class="navbar-search">
    <div class="position-relative">
        <a href="javascript:void(0);" class="navbar-search-icon"><span class="feather-icon"><i data-feather="search"></i></span></a>
        <input type="text" name="example-input1-group2" class="form-control" placeholder="Type here to Search">
        <a id="navbar_search_close" class="navbar-search-close" href="#"><span class="feather-icon"><i data-feather="x"></i></span></a>
    </div>
</form> --}}
<!-- /Top Navbar -->